#if IS_NET_8_0_OR_GREATER
namespace Epiforge.Extensions.Expressions.Observable;

/// <summary>
/// Performs the primitive conversions and operators of expression trees on boxed values, each written as the C# cast or operator which compiles to the same instruction the expression compiler emits, so that results, wrapping, overflow and division by zero agree with a compiled lambda
/// </summary>
static class ClosureOperations
{
    internal static Func<object?, object?, object?>? Binary(ExpressionType nodeType, TypeCode type) =>
        (nodeType, type) switch
        {
            (ExpressionType.Add, TypeCode.SByte) => static (l, r) => unchecked((sbyte)((sbyte)l! + (sbyte)r!)),
            (ExpressionType.Add, TypeCode.Byte) => static (l, r) => unchecked((byte)((byte)l! + (byte)r!)),
            (ExpressionType.Add, TypeCode.Int16) => static (l, r) => unchecked((short)((short)l! + (short)r!)),
            (ExpressionType.Add, TypeCode.UInt16) => static (l, r) => unchecked((ushort)((ushort)l! + (ushort)r!)),
            (ExpressionType.Add, TypeCode.Int32) => static (l, r) => unchecked((int)l! + (int)r!),
            (ExpressionType.Add, TypeCode.UInt32) => static (l, r) => unchecked((uint)l! + (uint)r!),
            (ExpressionType.Add, TypeCode.Int64) => static (l, r) => unchecked((long)l! + (long)r!),
            (ExpressionType.Add, TypeCode.UInt64) => static (l, r) => unchecked((ulong)l! + (ulong)r!),
            (ExpressionType.Add, TypeCode.Single) => static (l, r) => unchecked((float)l! + (float)r!),
            (ExpressionType.Add, TypeCode.Double) => static (l, r) => unchecked((double)l! + (double)r!),
            (ExpressionType.AddChecked, TypeCode.SByte) => static (l, r) => checked((sbyte)((sbyte)l! + (sbyte)r!)),
            (ExpressionType.AddChecked, TypeCode.Byte) => static (l, r) => checked((byte)((byte)l! + (byte)r!)),
            (ExpressionType.AddChecked, TypeCode.Int16) => static (l, r) => checked((short)((short)l! + (short)r!)),
            (ExpressionType.AddChecked, TypeCode.UInt16) => static (l, r) => checked((ushort)((ushort)l! + (ushort)r!)),
            (ExpressionType.AddChecked, TypeCode.Int32) => static (l, r) => checked((int)l! + (int)r!),
            (ExpressionType.AddChecked, TypeCode.UInt32) => static (l, r) => checked((uint)l! + (uint)r!),
            (ExpressionType.AddChecked, TypeCode.Int64) => static (l, r) => checked((long)l! + (long)r!),
            (ExpressionType.AddChecked, TypeCode.UInt64) => static (l, r) => checked((ulong)l! + (ulong)r!),
            (ExpressionType.AddChecked, TypeCode.Single) => static (l, r) => checked((float)l! + (float)r!),
            (ExpressionType.AddChecked, TypeCode.Double) => static (l, r) => checked((double)l! + (double)r!),
            (ExpressionType.Subtract, TypeCode.SByte) => static (l, r) => unchecked((sbyte)((sbyte)l! - (sbyte)r!)),
            (ExpressionType.Subtract, TypeCode.Byte) => static (l, r) => unchecked((byte)((byte)l! - (byte)r!)),
            (ExpressionType.Subtract, TypeCode.Int16) => static (l, r) => unchecked((short)((short)l! - (short)r!)),
            (ExpressionType.Subtract, TypeCode.UInt16) => static (l, r) => unchecked((ushort)((ushort)l! - (ushort)r!)),
            (ExpressionType.Subtract, TypeCode.Int32) => static (l, r) => unchecked((int)l! - (int)r!),
            (ExpressionType.Subtract, TypeCode.UInt32) => static (l, r) => unchecked((uint)l! - (uint)r!),
            (ExpressionType.Subtract, TypeCode.Int64) => static (l, r) => unchecked((long)l! - (long)r!),
            (ExpressionType.Subtract, TypeCode.UInt64) => static (l, r) => unchecked((ulong)l! - (ulong)r!),
            (ExpressionType.Subtract, TypeCode.Single) => static (l, r) => unchecked((float)l! - (float)r!),
            (ExpressionType.Subtract, TypeCode.Double) => static (l, r) => unchecked((double)l! - (double)r!),
            (ExpressionType.SubtractChecked, TypeCode.SByte) => static (l, r) => checked((sbyte)((sbyte)l! - (sbyte)r!)),
            (ExpressionType.SubtractChecked, TypeCode.Byte) => static (l, r) => checked((byte)((byte)l! - (byte)r!)),
            (ExpressionType.SubtractChecked, TypeCode.Int16) => static (l, r) => checked((short)((short)l! - (short)r!)),
            (ExpressionType.SubtractChecked, TypeCode.UInt16) => static (l, r) => checked((ushort)((ushort)l! - (ushort)r!)),
            (ExpressionType.SubtractChecked, TypeCode.Int32) => static (l, r) => checked((int)l! - (int)r!),
            (ExpressionType.SubtractChecked, TypeCode.UInt32) => static (l, r) => checked((uint)l! - (uint)r!),
            (ExpressionType.SubtractChecked, TypeCode.Int64) => static (l, r) => checked((long)l! - (long)r!),
            (ExpressionType.SubtractChecked, TypeCode.UInt64) => static (l, r) => checked((ulong)l! - (ulong)r!),
            (ExpressionType.SubtractChecked, TypeCode.Single) => static (l, r) => checked((float)l! - (float)r!),
            (ExpressionType.SubtractChecked, TypeCode.Double) => static (l, r) => checked((double)l! - (double)r!),
            (ExpressionType.Multiply, TypeCode.SByte) => static (l, r) => unchecked((sbyte)((sbyte)l! * (sbyte)r!)),
            (ExpressionType.Multiply, TypeCode.Byte) => static (l, r) => unchecked((byte)((byte)l! * (byte)r!)),
            (ExpressionType.Multiply, TypeCode.Int16) => static (l, r) => unchecked((short)((short)l! * (short)r!)),
            (ExpressionType.Multiply, TypeCode.UInt16) => static (l, r) => unchecked((ushort)((ushort)l! * (ushort)r!)),
            (ExpressionType.Multiply, TypeCode.Int32) => static (l, r) => unchecked((int)l! * (int)r!),
            (ExpressionType.Multiply, TypeCode.UInt32) => static (l, r) => unchecked((uint)l! * (uint)r!),
            (ExpressionType.Multiply, TypeCode.Int64) => static (l, r) => unchecked((long)l! * (long)r!),
            (ExpressionType.Multiply, TypeCode.UInt64) => static (l, r) => unchecked((ulong)l! * (ulong)r!),
            (ExpressionType.Multiply, TypeCode.Single) => static (l, r) => unchecked((float)l! * (float)r!),
            (ExpressionType.Multiply, TypeCode.Double) => static (l, r) => unchecked((double)l! * (double)r!),
            (ExpressionType.MultiplyChecked, TypeCode.SByte) => static (l, r) => checked((sbyte)((sbyte)l! * (sbyte)r!)),
            (ExpressionType.MultiplyChecked, TypeCode.Byte) => static (l, r) => checked((byte)((byte)l! * (byte)r!)),
            (ExpressionType.MultiplyChecked, TypeCode.Int16) => static (l, r) => checked((short)((short)l! * (short)r!)),
            (ExpressionType.MultiplyChecked, TypeCode.UInt16) => static (l, r) => checked((ushort)((ushort)l! * (ushort)r!)),
            (ExpressionType.MultiplyChecked, TypeCode.Int32) => static (l, r) => checked((int)l! * (int)r!),
            (ExpressionType.MultiplyChecked, TypeCode.UInt32) => static (l, r) => checked((uint)l! * (uint)r!),
            (ExpressionType.MultiplyChecked, TypeCode.Int64) => static (l, r) => checked((long)l! * (long)r!),
            (ExpressionType.MultiplyChecked, TypeCode.UInt64) => static (l, r) => checked((ulong)l! * (ulong)r!),
            (ExpressionType.MultiplyChecked, TypeCode.Single) => static (l, r) => checked((float)l! * (float)r!),
            (ExpressionType.MultiplyChecked, TypeCode.Double) => static (l, r) => checked((double)l! * (double)r!),
            (ExpressionType.Divide, TypeCode.SByte) => static (l, r) => unchecked((sbyte)((sbyte)l! / (sbyte)r!)),
            (ExpressionType.Divide, TypeCode.Byte) => static (l, r) => unchecked((byte)((byte)l! / (byte)r!)),
            (ExpressionType.Divide, TypeCode.Int16) => static (l, r) => unchecked((short)((short)l! / (short)r!)),
            (ExpressionType.Divide, TypeCode.UInt16) => static (l, r) => unchecked((ushort)((ushort)l! / (ushort)r!)),
            (ExpressionType.Divide, TypeCode.Int32) => static (l, r) => unchecked((int)l! / (int)r!),
            (ExpressionType.Divide, TypeCode.UInt32) => static (l, r) => unchecked((uint)l! / (uint)r!),
            (ExpressionType.Divide, TypeCode.Int64) => static (l, r) => unchecked((long)l! / (long)r!),
            (ExpressionType.Divide, TypeCode.UInt64) => static (l, r) => unchecked((ulong)l! / (ulong)r!),
            (ExpressionType.Divide, TypeCode.Single) => static (l, r) => unchecked((float)l! / (float)r!),
            (ExpressionType.Divide, TypeCode.Double) => static (l, r) => unchecked((double)l! / (double)r!),
            (ExpressionType.Modulo, TypeCode.SByte) => static (l, r) => unchecked((sbyte)((sbyte)l! % (sbyte)r!)),
            (ExpressionType.Modulo, TypeCode.Byte) => static (l, r) => unchecked((byte)((byte)l! % (byte)r!)),
            (ExpressionType.Modulo, TypeCode.Int16) => static (l, r) => unchecked((short)((short)l! % (short)r!)),
            (ExpressionType.Modulo, TypeCode.UInt16) => static (l, r) => unchecked((ushort)((ushort)l! % (ushort)r!)),
            (ExpressionType.Modulo, TypeCode.Int32) => static (l, r) => unchecked((int)l! % (int)r!),
            (ExpressionType.Modulo, TypeCode.UInt32) => static (l, r) => unchecked((uint)l! % (uint)r!),
            (ExpressionType.Modulo, TypeCode.Int64) => static (l, r) => unchecked((long)l! % (long)r!),
            (ExpressionType.Modulo, TypeCode.UInt64) => static (l, r) => unchecked((ulong)l! % (ulong)r!),
            (ExpressionType.Modulo, TypeCode.Single) => static (l, r) => unchecked((float)l! % (float)r!),
            (ExpressionType.Modulo, TypeCode.Double) => static (l, r) => unchecked((double)l! % (double)r!),
            (ExpressionType.And, TypeCode.SByte) => static (l, r) => (sbyte)((sbyte)l! & (sbyte)r!),
            (ExpressionType.And, TypeCode.Byte) => static (l, r) => (byte)((byte)l! & (byte)r!),
            (ExpressionType.And, TypeCode.Int16) => static (l, r) => (short)((short)l! & (short)r!),
            (ExpressionType.And, TypeCode.UInt16) => static (l, r) => (ushort)((ushort)l! & (ushort)r!),
            (ExpressionType.And, TypeCode.Int32) => static (l, r) => (int)l! & (int)r!,
            (ExpressionType.And, TypeCode.UInt32) => static (l, r) => (uint)l! & (uint)r!,
            (ExpressionType.And, TypeCode.Int64) => static (l, r) => (long)l! & (long)r!,
            (ExpressionType.And, TypeCode.UInt64) => static (l, r) => (ulong)l! & (ulong)r!,
            (ExpressionType.And, TypeCode.Boolean) => static (l, r) => BooleanBoxes.Box((bool)l! & (bool)r!),
            (ExpressionType.Or, TypeCode.SByte) => static (l, r) => (sbyte)((sbyte)l! | (sbyte)r!),
            (ExpressionType.Or, TypeCode.Byte) => static (l, r) => (byte)((byte)l! | (byte)r!),
            (ExpressionType.Or, TypeCode.Int16) => static (l, r) => (short)((short)l! | (short)r!),
            (ExpressionType.Or, TypeCode.UInt16) => static (l, r) => (ushort)((ushort)l! | (ushort)r!),
            (ExpressionType.Or, TypeCode.Int32) => static (l, r) => (int)l! | (int)r!,
            (ExpressionType.Or, TypeCode.UInt32) => static (l, r) => (uint)l! | (uint)r!,
            (ExpressionType.Or, TypeCode.Int64) => static (l, r) => (long)l! | (long)r!,
            (ExpressionType.Or, TypeCode.UInt64) => static (l, r) => (ulong)l! | (ulong)r!,
            (ExpressionType.Or, TypeCode.Boolean) => static (l, r) => BooleanBoxes.Box((bool)l! | (bool)r!),
            (ExpressionType.ExclusiveOr, TypeCode.SByte) => static (l, r) => (sbyte)((sbyte)l! ^ (sbyte)r!),
            (ExpressionType.ExclusiveOr, TypeCode.Byte) => static (l, r) => (byte)((byte)l! ^ (byte)r!),
            (ExpressionType.ExclusiveOr, TypeCode.Int16) => static (l, r) => (short)((short)l! ^ (short)r!),
            (ExpressionType.ExclusiveOr, TypeCode.UInt16) => static (l, r) => (ushort)((ushort)l! ^ (ushort)r!),
            (ExpressionType.ExclusiveOr, TypeCode.Int32) => static (l, r) => (int)l! ^ (int)r!,
            (ExpressionType.ExclusiveOr, TypeCode.UInt32) => static (l, r) => (uint)l! ^ (uint)r!,
            (ExpressionType.ExclusiveOr, TypeCode.Int64) => static (l, r) => (long)l! ^ (long)r!,
            (ExpressionType.ExclusiveOr, TypeCode.UInt64) => static (l, r) => (ulong)l! ^ (ulong)r!,
            (ExpressionType.ExclusiveOr, TypeCode.Boolean) => static (l, r) => BooleanBoxes.Box((bool)l! ^ (bool)r!),
            (ExpressionType.LeftShift, TypeCode.SByte) => static (l, r) => unchecked((sbyte)((sbyte)l! << (int)r!)),
            (ExpressionType.LeftShift, TypeCode.Byte) => static (l, r) => unchecked((byte)((byte)l! << (int)r!)),
            (ExpressionType.LeftShift, TypeCode.Int16) => static (l, r) => unchecked((short)((short)l! << (int)r!)),
            (ExpressionType.LeftShift, TypeCode.UInt16) => static (l, r) => unchecked((ushort)((ushort)l! << (int)r!)),
            (ExpressionType.LeftShift, TypeCode.Int32) => static (l, r) => unchecked((int)l! << (int)r!),
            (ExpressionType.LeftShift, TypeCode.UInt32) => static (l, r) => unchecked((uint)l! << (int)r!),
            (ExpressionType.LeftShift, TypeCode.Int64) => static (l, r) => unchecked((long)l! << (int)r!),
            (ExpressionType.LeftShift, TypeCode.UInt64) => static (l, r) => unchecked((ulong)l! << (int)r!),
            (ExpressionType.RightShift, TypeCode.SByte) => static (l, r) => unchecked((sbyte)((sbyte)l! >> (int)r!)),
            (ExpressionType.RightShift, TypeCode.Byte) => static (l, r) => unchecked((byte)((byte)l! >> (int)r!)),
            (ExpressionType.RightShift, TypeCode.Int16) => static (l, r) => unchecked((short)((short)l! >> (int)r!)),
            (ExpressionType.RightShift, TypeCode.UInt16) => static (l, r) => unchecked((ushort)((ushort)l! >> (int)r!)),
            (ExpressionType.RightShift, TypeCode.Int32) => static (l, r) => unchecked((int)l! >> (int)r!),
            (ExpressionType.RightShift, TypeCode.UInt32) => static (l, r) => unchecked((uint)l! >> (int)r!),
            (ExpressionType.RightShift, TypeCode.Int64) => static (l, r) => unchecked((long)l! >> (int)r!),
            (ExpressionType.RightShift, TypeCode.UInt64) => static (l, r) => unchecked((ulong)l! >> (int)r!),
            (ExpressionType.LessThan, TypeCode.SByte) => static (l, r) => BooleanBoxes.Box((sbyte)l! < (sbyte)r!),
            (ExpressionType.LessThan, TypeCode.Byte) => static (l, r) => BooleanBoxes.Box((byte)l! < (byte)r!),
            (ExpressionType.LessThan, TypeCode.Int16) => static (l, r) => BooleanBoxes.Box((short)l! < (short)r!),
            (ExpressionType.LessThan, TypeCode.UInt16) => static (l, r) => BooleanBoxes.Box((ushort)l! < (ushort)r!),
            (ExpressionType.LessThan, TypeCode.Int32) => static (l, r) => BooleanBoxes.Box((int)l! < (int)r!),
            (ExpressionType.LessThan, TypeCode.UInt32) => static (l, r) => BooleanBoxes.Box((uint)l! < (uint)r!),
            (ExpressionType.LessThan, TypeCode.Int64) => static (l, r) => BooleanBoxes.Box((long)l! < (long)r!),
            (ExpressionType.LessThan, TypeCode.UInt64) => static (l, r) => BooleanBoxes.Box((ulong)l! < (ulong)r!),
            (ExpressionType.LessThan, TypeCode.Char) => static (l, r) => BooleanBoxes.Box((char)l! < (char)r!),
            (ExpressionType.LessThan, TypeCode.Single) => static (l, r) => BooleanBoxes.Box((float)l! < (float)r!),
            (ExpressionType.LessThan, TypeCode.Double) => static (l, r) => BooleanBoxes.Box((double)l! < (double)r!),
            (ExpressionType.LessThanOrEqual, TypeCode.SByte) => static (l, r) => BooleanBoxes.Box((sbyte)l! <= (sbyte)r!),
            (ExpressionType.LessThanOrEqual, TypeCode.Byte) => static (l, r) => BooleanBoxes.Box((byte)l! <= (byte)r!),
            (ExpressionType.LessThanOrEqual, TypeCode.Int16) => static (l, r) => BooleanBoxes.Box((short)l! <= (short)r!),
            (ExpressionType.LessThanOrEqual, TypeCode.UInt16) => static (l, r) => BooleanBoxes.Box((ushort)l! <= (ushort)r!),
            (ExpressionType.LessThanOrEqual, TypeCode.Int32) => static (l, r) => BooleanBoxes.Box((int)l! <= (int)r!),
            (ExpressionType.LessThanOrEqual, TypeCode.UInt32) => static (l, r) => BooleanBoxes.Box((uint)l! <= (uint)r!),
            (ExpressionType.LessThanOrEqual, TypeCode.Int64) => static (l, r) => BooleanBoxes.Box((long)l! <= (long)r!),
            (ExpressionType.LessThanOrEqual, TypeCode.UInt64) => static (l, r) => BooleanBoxes.Box((ulong)l! <= (ulong)r!),
            (ExpressionType.LessThanOrEqual, TypeCode.Char) => static (l, r) => BooleanBoxes.Box((char)l! <= (char)r!),
            (ExpressionType.LessThanOrEqual, TypeCode.Single) => static (l, r) => BooleanBoxes.Box((float)l! <= (float)r!),
            (ExpressionType.LessThanOrEqual, TypeCode.Double) => static (l, r) => BooleanBoxes.Box((double)l! <= (double)r!),
            (ExpressionType.GreaterThan, TypeCode.SByte) => static (l, r) => BooleanBoxes.Box((sbyte)l! > (sbyte)r!),
            (ExpressionType.GreaterThan, TypeCode.Byte) => static (l, r) => BooleanBoxes.Box((byte)l! > (byte)r!),
            (ExpressionType.GreaterThan, TypeCode.Int16) => static (l, r) => BooleanBoxes.Box((short)l! > (short)r!),
            (ExpressionType.GreaterThan, TypeCode.UInt16) => static (l, r) => BooleanBoxes.Box((ushort)l! > (ushort)r!),
            (ExpressionType.GreaterThan, TypeCode.Int32) => static (l, r) => BooleanBoxes.Box((int)l! > (int)r!),
            (ExpressionType.GreaterThan, TypeCode.UInt32) => static (l, r) => BooleanBoxes.Box((uint)l! > (uint)r!),
            (ExpressionType.GreaterThan, TypeCode.Int64) => static (l, r) => BooleanBoxes.Box((long)l! > (long)r!),
            (ExpressionType.GreaterThan, TypeCode.UInt64) => static (l, r) => BooleanBoxes.Box((ulong)l! > (ulong)r!),
            (ExpressionType.GreaterThan, TypeCode.Char) => static (l, r) => BooleanBoxes.Box((char)l! > (char)r!),
            (ExpressionType.GreaterThan, TypeCode.Single) => static (l, r) => BooleanBoxes.Box((float)l! > (float)r!),
            (ExpressionType.GreaterThan, TypeCode.Double) => static (l, r) => BooleanBoxes.Box((double)l! > (double)r!),
            (ExpressionType.GreaterThanOrEqual, TypeCode.SByte) => static (l, r) => BooleanBoxes.Box((sbyte)l! >= (sbyte)r!),
            (ExpressionType.GreaterThanOrEqual, TypeCode.Byte) => static (l, r) => BooleanBoxes.Box((byte)l! >= (byte)r!),
            (ExpressionType.GreaterThanOrEqual, TypeCode.Int16) => static (l, r) => BooleanBoxes.Box((short)l! >= (short)r!),
            (ExpressionType.GreaterThanOrEqual, TypeCode.UInt16) => static (l, r) => BooleanBoxes.Box((ushort)l! >= (ushort)r!),
            (ExpressionType.GreaterThanOrEqual, TypeCode.Int32) => static (l, r) => BooleanBoxes.Box((int)l! >= (int)r!),
            (ExpressionType.GreaterThanOrEqual, TypeCode.UInt32) => static (l, r) => BooleanBoxes.Box((uint)l! >= (uint)r!),
            (ExpressionType.GreaterThanOrEqual, TypeCode.Int64) => static (l, r) => BooleanBoxes.Box((long)l! >= (long)r!),
            (ExpressionType.GreaterThanOrEqual, TypeCode.UInt64) => static (l, r) => BooleanBoxes.Box((ulong)l! >= (ulong)r!),
            (ExpressionType.GreaterThanOrEqual, TypeCode.Char) => static (l, r) => BooleanBoxes.Box((char)l! >= (char)r!),
            (ExpressionType.GreaterThanOrEqual, TypeCode.Single) => static (l, r) => BooleanBoxes.Box((float)l! >= (float)r!),
            (ExpressionType.GreaterThanOrEqual, TypeCode.Double) => static (l, r) => BooleanBoxes.Box((double)l! >= (double)r!),
            (ExpressionType.Equal, TypeCode.SByte) => static (l, r) => BooleanBoxes.Box((sbyte)l! == (sbyte)r!),
            (ExpressionType.Equal, TypeCode.Byte) => static (l, r) => BooleanBoxes.Box((byte)l! == (byte)r!),
            (ExpressionType.Equal, TypeCode.Int16) => static (l, r) => BooleanBoxes.Box((short)l! == (short)r!),
            (ExpressionType.Equal, TypeCode.UInt16) => static (l, r) => BooleanBoxes.Box((ushort)l! == (ushort)r!),
            (ExpressionType.Equal, TypeCode.Int32) => static (l, r) => BooleanBoxes.Box((int)l! == (int)r!),
            (ExpressionType.Equal, TypeCode.UInt32) => static (l, r) => BooleanBoxes.Box((uint)l! == (uint)r!),
            (ExpressionType.Equal, TypeCode.Int64) => static (l, r) => BooleanBoxes.Box((long)l! == (long)r!),
            (ExpressionType.Equal, TypeCode.UInt64) => static (l, r) => BooleanBoxes.Box((ulong)l! == (ulong)r!),
            (ExpressionType.Equal, TypeCode.Char) => static (l, r) => BooleanBoxes.Box((char)l! == (char)r!),
            (ExpressionType.Equal, TypeCode.Single) => static (l, r) => BooleanBoxes.Box((float)l! == (float)r!),
            (ExpressionType.Equal, TypeCode.Double) => static (l, r) => BooleanBoxes.Box((double)l! == (double)r!),
            (ExpressionType.Equal, TypeCode.Boolean) => static (l, r) => BooleanBoxes.Box((bool)l! == (bool)r!),
            (ExpressionType.NotEqual, TypeCode.SByte) => static (l, r) => BooleanBoxes.Box((sbyte)l! != (sbyte)r!),
            (ExpressionType.NotEqual, TypeCode.Byte) => static (l, r) => BooleanBoxes.Box((byte)l! != (byte)r!),
            (ExpressionType.NotEqual, TypeCode.Int16) => static (l, r) => BooleanBoxes.Box((short)l! != (short)r!),
            (ExpressionType.NotEqual, TypeCode.UInt16) => static (l, r) => BooleanBoxes.Box((ushort)l! != (ushort)r!),
            (ExpressionType.NotEqual, TypeCode.Int32) => static (l, r) => BooleanBoxes.Box((int)l! != (int)r!),
            (ExpressionType.NotEqual, TypeCode.UInt32) => static (l, r) => BooleanBoxes.Box((uint)l! != (uint)r!),
            (ExpressionType.NotEqual, TypeCode.Int64) => static (l, r) => BooleanBoxes.Box((long)l! != (long)r!),
            (ExpressionType.NotEqual, TypeCode.UInt64) => static (l, r) => BooleanBoxes.Box((ulong)l! != (ulong)r!),
            (ExpressionType.NotEqual, TypeCode.Char) => static (l, r) => BooleanBoxes.Box((char)l! != (char)r!),
            (ExpressionType.NotEqual, TypeCode.Single) => static (l, r) => BooleanBoxes.Box((float)l! != (float)r!),
            (ExpressionType.NotEqual, TypeCode.Double) => static (l, r) => BooleanBoxes.Box((double)l! != (double)r!),
            (ExpressionType.NotEqual, TypeCode.Boolean) => static (l, r) => BooleanBoxes.Box((bool)l! != (bool)r!),
            _ => null
        };

    internal static Func<object?, object?>? Conversion(TypeCode from, TypeCode to, bool @checked) =>
        (from, to, @checked) switch
        {
            (TypeCode.SByte, TypeCode.SByte, false) => static value => unchecked((sbyte)(sbyte)value!),
            (TypeCode.SByte, TypeCode.SByte, true) => static value => checked((sbyte)(sbyte)value!),
            (TypeCode.SByte, TypeCode.Byte, false) => static value => unchecked((byte)(sbyte)value!),
            (TypeCode.SByte, TypeCode.Byte, true) => static value => checked((byte)(sbyte)value!),
            (TypeCode.SByte, TypeCode.Int16, false) => static value => unchecked((short)(sbyte)value!),
            (TypeCode.SByte, TypeCode.Int16, true) => static value => checked((short)(sbyte)value!),
            (TypeCode.SByte, TypeCode.UInt16, false) => static value => unchecked((ushort)(sbyte)value!),
            (TypeCode.SByte, TypeCode.UInt16, true) => static value => checked((ushort)(sbyte)value!),
            (TypeCode.SByte, TypeCode.Int32, false) => static value => unchecked((int)(sbyte)value!),
            (TypeCode.SByte, TypeCode.Int32, true) => static value => checked((int)(sbyte)value!),
            (TypeCode.SByte, TypeCode.UInt32, false) => static value => unchecked((uint)(sbyte)value!),
            (TypeCode.SByte, TypeCode.UInt32, true) => static value => checked((uint)(sbyte)value!),
            (TypeCode.SByte, TypeCode.Int64, false) => static value => unchecked((long)(sbyte)value!),
            (TypeCode.SByte, TypeCode.Int64, true) => static value => checked((long)(sbyte)value!),
            (TypeCode.SByte, TypeCode.UInt64, false) => static value => unchecked((ulong)(sbyte)value!),
            (TypeCode.SByte, TypeCode.UInt64, true) => static value => checked((ulong)(sbyte)value!),
            (TypeCode.SByte, TypeCode.Char, false) => static value => unchecked((char)(sbyte)value!),
            (TypeCode.SByte, TypeCode.Char, true) => static value => checked((char)(sbyte)value!),
            (TypeCode.SByte, TypeCode.Single, false) => static value => unchecked((float)(sbyte)value!),
            (TypeCode.SByte, TypeCode.Single, true) => static value => checked((float)(sbyte)value!),
            (TypeCode.SByte, TypeCode.Double, false) => static value => unchecked((double)(sbyte)value!),
            (TypeCode.SByte, TypeCode.Double, true) => static value => checked((double)(sbyte)value!),
            (TypeCode.Byte, TypeCode.SByte, false) => static value => unchecked((sbyte)(byte)value!),
            (TypeCode.Byte, TypeCode.SByte, true) => static value => checked((sbyte)(byte)value!),
            (TypeCode.Byte, TypeCode.Byte, false) => static value => unchecked((byte)(byte)value!),
            (TypeCode.Byte, TypeCode.Byte, true) => static value => checked((byte)(byte)value!),
            (TypeCode.Byte, TypeCode.Int16, false) => static value => unchecked((short)(byte)value!),
            (TypeCode.Byte, TypeCode.Int16, true) => static value => checked((short)(byte)value!),
            (TypeCode.Byte, TypeCode.UInt16, false) => static value => unchecked((ushort)(byte)value!),
            (TypeCode.Byte, TypeCode.UInt16, true) => static value => checked((ushort)(byte)value!),
            (TypeCode.Byte, TypeCode.Int32, false) => static value => unchecked((int)(byte)value!),
            (TypeCode.Byte, TypeCode.Int32, true) => static value => checked((int)(byte)value!),
            (TypeCode.Byte, TypeCode.UInt32, false) => static value => unchecked((uint)(byte)value!),
            (TypeCode.Byte, TypeCode.UInt32, true) => static value => checked((uint)(byte)value!),
            (TypeCode.Byte, TypeCode.Int64, false) => static value => unchecked((long)(byte)value!),
            (TypeCode.Byte, TypeCode.Int64, true) => static value => checked((long)(byte)value!),
            (TypeCode.Byte, TypeCode.UInt64, false) => static value => unchecked((ulong)(byte)value!),
            (TypeCode.Byte, TypeCode.UInt64, true) => static value => checked((ulong)(byte)value!),
            (TypeCode.Byte, TypeCode.Char, false) => static value => unchecked((char)(byte)value!),
            (TypeCode.Byte, TypeCode.Char, true) => static value => checked((char)(byte)value!),
            (TypeCode.Byte, TypeCode.Single, false) => static value => unchecked((float)(byte)value!),
            (TypeCode.Byte, TypeCode.Single, true) => static value => checked((float)(byte)value!),
            (TypeCode.Byte, TypeCode.Double, false) => static value => unchecked((double)(byte)value!),
            (TypeCode.Byte, TypeCode.Double, true) => static value => checked((double)(byte)value!),
            (TypeCode.Int16, TypeCode.SByte, false) => static value => unchecked((sbyte)(short)value!),
            (TypeCode.Int16, TypeCode.SByte, true) => static value => checked((sbyte)(short)value!),
            (TypeCode.Int16, TypeCode.Byte, false) => static value => unchecked((byte)(short)value!),
            (TypeCode.Int16, TypeCode.Byte, true) => static value => checked((byte)(short)value!),
            (TypeCode.Int16, TypeCode.Int16, false) => static value => unchecked((short)(short)value!),
            (TypeCode.Int16, TypeCode.Int16, true) => static value => checked((short)(short)value!),
            (TypeCode.Int16, TypeCode.UInt16, false) => static value => unchecked((ushort)(short)value!),
            (TypeCode.Int16, TypeCode.UInt16, true) => static value => checked((ushort)(short)value!),
            (TypeCode.Int16, TypeCode.Int32, false) => static value => unchecked((int)(short)value!),
            (TypeCode.Int16, TypeCode.Int32, true) => static value => checked((int)(short)value!),
            (TypeCode.Int16, TypeCode.UInt32, false) => static value => unchecked((uint)(short)value!),
            (TypeCode.Int16, TypeCode.UInt32, true) => static value => checked((uint)(short)value!),
            (TypeCode.Int16, TypeCode.Int64, false) => static value => unchecked((long)(short)value!),
            (TypeCode.Int16, TypeCode.Int64, true) => static value => checked((long)(short)value!),
            (TypeCode.Int16, TypeCode.UInt64, false) => static value => unchecked((ulong)(short)value!),
            (TypeCode.Int16, TypeCode.UInt64, true) => static value => checked((ulong)(short)value!),
            (TypeCode.Int16, TypeCode.Char, false) => static value => unchecked((char)(short)value!),
            (TypeCode.Int16, TypeCode.Char, true) => static value => checked((char)(short)value!),
            (TypeCode.Int16, TypeCode.Single, false) => static value => unchecked((float)(short)value!),
            (TypeCode.Int16, TypeCode.Single, true) => static value => checked((float)(short)value!),
            (TypeCode.Int16, TypeCode.Double, false) => static value => unchecked((double)(short)value!),
            (TypeCode.Int16, TypeCode.Double, true) => static value => checked((double)(short)value!),
            (TypeCode.UInt16, TypeCode.SByte, false) => static value => unchecked((sbyte)(ushort)value!),
            (TypeCode.UInt16, TypeCode.SByte, true) => static value => checked((sbyte)(ushort)value!),
            (TypeCode.UInt16, TypeCode.Byte, false) => static value => unchecked((byte)(ushort)value!),
            (TypeCode.UInt16, TypeCode.Byte, true) => static value => checked((byte)(ushort)value!),
            (TypeCode.UInt16, TypeCode.Int16, false) => static value => unchecked((short)(ushort)value!),
            (TypeCode.UInt16, TypeCode.Int16, true) => static value => checked((short)(ushort)value!),
            (TypeCode.UInt16, TypeCode.UInt16, false) => static value => unchecked((ushort)(ushort)value!),
            (TypeCode.UInt16, TypeCode.UInt16, true) => static value => checked((ushort)(ushort)value!),
            (TypeCode.UInt16, TypeCode.Int32, false) => static value => unchecked((int)(ushort)value!),
            (TypeCode.UInt16, TypeCode.Int32, true) => static value => checked((int)(ushort)value!),
            (TypeCode.UInt16, TypeCode.UInt32, false) => static value => unchecked((uint)(ushort)value!),
            (TypeCode.UInt16, TypeCode.UInt32, true) => static value => checked((uint)(ushort)value!),
            (TypeCode.UInt16, TypeCode.Int64, false) => static value => unchecked((long)(ushort)value!),
            (TypeCode.UInt16, TypeCode.Int64, true) => static value => checked((long)(ushort)value!),
            (TypeCode.UInt16, TypeCode.UInt64, false) => static value => unchecked((ulong)(ushort)value!),
            (TypeCode.UInt16, TypeCode.UInt64, true) => static value => checked((ulong)(ushort)value!),
            (TypeCode.UInt16, TypeCode.Char, false) => static value => unchecked((char)(ushort)value!),
            (TypeCode.UInt16, TypeCode.Char, true) => static value => checked((char)(ushort)value!),
            (TypeCode.UInt16, TypeCode.Single, false) => static value => unchecked((float)(ushort)value!),
            (TypeCode.UInt16, TypeCode.Single, true) => static value => checked((float)(ushort)value!),
            (TypeCode.UInt16, TypeCode.Double, false) => static value => unchecked((double)(ushort)value!),
            (TypeCode.UInt16, TypeCode.Double, true) => static value => checked((double)(ushort)value!),
            (TypeCode.Int32, TypeCode.SByte, false) => static value => unchecked((sbyte)(int)value!),
            (TypeCode.Int32, TypeCode.SByte, true) => static value => checked((sbyte)(int)value!),
            (TypeCode.Int32, TypeCode.Byte, false) => static value => unchecked((byte)(int)value!),
            (TypeCode.Int32, TypeCode.Byte, true) => static value => checked((byte)(int)value!),
            (TypeCode.Int32, TypeCode.Int16, false) => static value => unchecked((short)(int)value!),
            (TypeCode.Int32, TypeCode.Int16, true) => static value => checked((short)(int)value!),
            (TypeCode.Int32, TypeCode.UInt16, false) => static value => unchecked((ushort)(int)value!),
            (TypeCode.Int32, TypeCode.UInt16, true) => static value => checked((ushort)(int)value!),
            (TypeCode.Int32, TypeCode.Int32, false) => static value => unchecked((int)(int)value!),
            (TypeCode.Int32, TypeCode.Int32, true) => static value => checked((int)(int)value!),
            (TypeCode.Int32, TypeCode.UInt32, false) => static value => unchecked((uint)(int)value!),
            (TypeCode.Int32, TypeCode.UInt32, true) => static value => checked((uint)(int)value!),
            (TypeCode.Int32, TypeCode.Int64, false) => static value => unchecked((long)(int)value!),
            (TypeCode.Int32, TypeCode.Int64, true) => static value => checked((long)(int)value!),
            (TypeCode.Int32, TypeCode.UInt64, false) => static value => unchecked((ulong)(int)value!),
            (TypeCode.Int32, TypeCode.UInt64, true) => static value => checked((ulong)(int)value!),
            (TypeCode.Int32, TypeCode.Char, false) => static value => unchecked((char)(int)value!),
            (TypeCode.Int32, TypeCode.Char, true) => static value => checked((char)(int)value!),
            (TypeCode.Int32, TypeCode.Single, false) => static value => unchecked((float)(int)value!),
            (TypeCode.Int32, TypeCode.Single, true) => static value => checked((float)(int)value!),
            (TypeCode.Int32, TypeCode.Double, false) => static value => unchecked((double)(int)value!),
            (TypeCode.Int32, TypeCode.Double, true) => static value => checked((double)(int)value!),
            (TypeCode.UInt32, TypeCode.SByte, false) => static value => unchecked((sbyte)(uint)value!),
            (TypeCode.UInt32, TypeCode.SByte, true) => static value => checked((sbyte)(uint)value!),
            (TypeCode.UInt32, TypeCode.Byte, false) => static value => unchecked((byte)(uint)value!),
            (TypeCode.UInt32, TypeCode.Byte, true) => static value => checked((byte)(uint)value!),
            (TypeCode.UInt32, TypeCode.Int16, false) => static value => unchecked((short)(uint)value!),
            (TypeCode.UInt32, TypeCode.Int16, true) => static value => checked((short)(uint)value!),
            (TypeCode.UInt32, TypeCode.UInt16, false) => static value => unchecked((ushort)(uint)value!),
            (TypeCode.UInt32, TypeCode.UInt16, true) => static value => checked((ushort)(uint)value!),
            (TypeCode.UInt32, TypeCode.Int32, false) => static value => unchecked((int)(uint)value!),
            (TypeCode.UInt32, TypeCode.Int32, true) => static value => checked((int)(uint)value!),
            (TypeCode.UInt32, TypeCode.UInt32, false) => static value => unchecked((uint)(uint)value!),
            (TypeCode.UInt32, TypeCode.UInt32, true) => static value => checked((uint)(uint)value!),
            (TypeCode.UInt32, TypeCode.Int64, false) => static value => unchecked((long)(uint)value!),
            (TypeCode.UInt32, TypeCode.Int64, true) => static value => checked((long)(uint)value!),
            (TypeCode.UInt32, TypeCode.UInt64, false) => static value => unchecked((ulong)(uint)value!),
            (TypeCode.UInt32, TypeCode.UInt64, true) => static value => checked((ulong)(uint)value!),
            (TypeCode.UInt32, TypeCode.Char, false) => static value => unchecked((char)(uint)value!),
            (TypeCode.UInt32, TypeCode.Char, true) => static value => checked((char)(uint)value!),
            (TypeCode.UInt32, TypeCode.Single, false) => static value => unchecked((float)(uint)value!),
            (TypeCode.UInt32, TypeCode.Single, true) => static value => checked((float)(uint)value!),
            (TypeCode.UInt32, TypeCode.Double, false) => static value => unchecked((double)(uint)value!),
            (TypeCode.UInt32, TypeCode.Double, true) => static value => checked((double)(uint)value!),
            (TypeCode.Int64, TypeCode.SByte, false) => static value => unchecked((sbyte)(long)value!),
            (TypeCode.Int64, TypeCode.SByte, true) => static value => checked((sbyte)(long)value!),
            (TypeCode.Int64, TypeCode.Byte, false) => static value => unchecked((byte)(long)value!),
            (TypeCode.Int64, TypeCode.Byte, true) => static value => checked((byte)(long)value!),
            (TypeCode.Int64, TypeCode.Int16, false) => static value => unchecked((short)(long)value!),
            (TypeCode.Int64, TypeCode.Int16, true) => static value => checked((short)(long)value!),
            (TypeCode.Int64, TypeCode.UInt16, false) => static value => unchecked((ushort)(long)value!),
            (TypeCode.Int64, TypeCode.UInt16, true) => static value => checked((ushort)(long)value!),
            (TypeCode.Int64, TypeCode.Int32, false) => static value => unchecked((int)(long)value!),
            (TypeCode.Int64, TypeCode.Int32, true) => static value => checked((int)(long)value!),
            (TypeCode.Int64, TypeCode.UInt32, false) => static value => unchecked((uint)(long)value!),
            (TypeCode.Int64, TypeCode.UInt32, true) => static value => checked((uint)(long)value!),
            (TypeCode.Int64, TypeCode.Int64, false) => static value => unchecked((long)(long)value!),
            (TypeCode.Int64, TypeCode.Int64, true) => static value => checked((long)(long)value!),
            (TypeCode.Int64, TypeCode.UInt64, false) => static value => unchecked((ulong)(long)value!),
            (TypeCode.Int64, TypeCode.UInt64, true) => static value => checked((ulong)(long)value!),
            (TypeCode.Int64, TypeCode.Char, false) => static value => unchecked((char)(long)value!),
            (TypeCode.Int64, TypeCode.Char, true) => static value => checked((char)(long)value!),
            (TypeCode.Int64, TypeCode.Single, false) => static value => unchecked((float)(long)value!),
            (TypeCode.Int64, TypeCode.Single, true) => static value => checked((float)(long)value!),
            (TypeCode.Int64, TypeCode.Double, false) => static value => unchecked((double)(long)value!),
            (TypeCode.Int64, TypeCode.Double, true) => static value => checked((double)(long)value!),
            (TypeCode.UInt64, TypeCode.SByte, false) => static value => unchecked((sbyte)(ulong)value!),
            (TypeCode.UInt64, TypeCode.SByte, true) => static value => checked((sbyte)(ulong)value!),
            (TypeCode.UInt64, TypeCode.Byte, false) => static value => unchecked((byte)(ulong)value!),
            (TypeCode.UInt64, TypeCode.Byte, true) => static value => checked((byte)(ulong)value!),
            (TypeCode.UInt64, TypeCode.Int16, false) => static value => unchecked((short)(ulong)value!),
            (TypeCode.UInt64, TypeCode.Int16, true) => static value => checked((short)(ulong)value!),
            (TypeCode.UInt64, TypeCode.UInt16, false) => static value => unchecked((ushort)(ulong)value!),
            (TypeCode.UInt64, TypeCode.UInt16, true) => static value => checked((ushort)(ulong)value!),
            (TypeCode.UInt64, TypeCode.Int32, false) => static value => unchecked((int)(ulong)value!),
            (TypeCode.UInt64, TypeCode.Int32, true) => static value => checked((int)(ulong)value!),
            (TypeCode.UInt64, TypeCode.UInt32, false) => static value => unchecked((uint)(ulong)value!),
            (TypeCode.UInt64, TypeCode.UInt32, true) => static value => checked((uint)(ulong)value!),
            (TypeCode.UInt64, TypeCode.Int64, false) => static value => unchecked((long)(ulong)value!),
            (TypeCode.UInt64, TypeCode.Int64, true) => static value => checked((long)(ulong)value!),
            (TypeCode.UInt64, TypeCode.UInt64, false) => static value => unchecked((ulong)(ulong)value!),
            (TypeCode.UInt64, TypeCode.UInt64, true) => static value => checked((ulong)(ulong)value!),
            (TypeCode.UInt64, TypeCode.Char, false) => static value => unchecked((char)(ulong)value!),
            (TypeCode.UInt64, TypeCode.Char, true) => static value => checked((char)(ulong)value!),
            (TypeCode.UInt64, TypeCode.Single, false) => static value => unchecked((float)(ulong)value!),
            (TypeCode.UInt64, TypeCode.Single, true) => static value => checked((float)(ulong)value!),
            (TypeCode.UInt64, TypeCode.Double, false) => static value => unchecked((double)(ulong)value!),
            (TypeCode.UInt64, TypeCode.Double, true) => static value => checked((double)(ulong)value!),
            (TypeCode.Char, TypeCode.SByte, false) => static value => unchecked((sbyte)(char)value!),
            (TypeCode.Char, TypeCode.SByte, true) => static value => checked((sbyte)(char)value!),
            (TypeCode.Char, TypeCode.Byte, false) => static value => unchecked((byte)(char)value!),
            (TypeCode.Char, TypeCode.Byte, true) => static value => checked((byte)(char)value!),
            (TypeCode.Char, TypeCode.Int16, false) => static value => unchecked((short)(char)value!),
            (TypeCode.Char, TypeCode.Int16, true) => static value => checked((short)(char)value!),
            (TypeCode.Char, TypeCode.UInt16, false) => static value => unchecked((ushort)(char)value!),
            (TypeCode.Char, TypeCode.UInt16, true) => static value => checked((ushort)(char)value!),
            (TypeCode.Char, TypeCode.Int32, false) => static value => unchecked((int)(char)value!),
            (TypeCode.Char, TypeCode.Int32, true) => static value => checked((int)(char)value!),
            (TypeCode.Char, TypeCode.UInt32, false) => static value => unchecked((uint)(char)value!),
            (TypeCode.Char, TypeCode.UInt32, true) => static value => checked((uint)(char)value!),
            (TypeCode.Char, TypeCode.Int64, false) => static value => unchecked((long)(char)value!),
            (TypeCode.Char, TypeCode.Int64, true) => static value => checked((long)(char)value!),
            (TypeCode.Char, TypeCode.UInt64, false) => static value => unchecked((ulong)(char)value!),
            (TypeCode.Char, TypeCode.UInt64, true) => static value => checked((ulong)(char)value!),
            (TypeCode.Char, TypeCode.Char, false) => static value => unchecked((char)(char)value!),
            (TypeCode.Char, TypeCode.Char, true) => static value => checked((char)(char)value!),
            (TypeCode.Char, TypeCode.Single, false) => static value => unchecked((float)(char)value!),
            (TypeCode.Char, TypeCode.Single, true) => static value => checked((float)(char)value!),
            (TypeCode.Char, TypeCode.Double, false) => static value => unchecked((double)(char)value!),
            (TypeCode.Char, TypeCode.Double, true) => static value => checked((double)(char)value!),
            (TypeCode.Single, TypeCode.SByte, false) => static value => unchecked((sbyte)(float)value!),
            (TypeCode.Single, TypeCode.SByte, true) => static value => checked((sbyte)(float)value!),
            (TypeCode.Single, TypeCode.Byte, false) => static value => unchecked((byte)(float)value!),
            (TypeCode.Single, TypeCode.Byte, true) => static value => checked((byte)(float)value!),
            (TypeCode.Single, TypeCode.Int16, false) => static value => unchecked((short)(float)value!),
            (TypeCode.Single, TypeCode.Int16, true) => static value => checked((short)(float)value!),
            (TypeCode.Single, TypeCode.UInt16, false) => static value => unchecked((ushort)(float)value!),
            (TypeCode.Single, TypeCode.UInt16, true) => static value => checked((ushort)(float)value!),
            (TypeCode.Single, TypeCode.Int32, false) => static value => unchecked((int)(float)value!),
            (TypeCode.Single, TypeCode.Int32, true) => static value => checked((int)(float)value!),
            (TypeCode.Single, TypeCode.UInt32, false) => static value => unchecked((uint)(float)value!),
            (TypeCode.Single, TypeCode.UInt32, true) => static value => checked((uint)(float)value!),
            (TypeCode.Single, TypeCode.Int64, false) => static value => unchecked((long)(float)value!),
            (TypeCode.Single, TypeCode.Int64, true) => static value => checked((long)(float)value!),
            (TypeCode.Single, TypeCode.UInt64, false) => static value => unchecked((ulong)(float)value!),
            (TypeCode.Single, TypeCode.UInt64, true) => static value => checked((ulong)(float)value!),
            (TypeCode.Single, TypeCode.Char, false) => static value => unchecked((char)(float)value!),
            (TypeCode.Single, TypeCode.Char, true) => static value => checked((char)(float)value!),
            (TypeCode.Single, TypeCode.Single, false) => static value => unchecked((float)(float)value!),
            (TypeCode.Single, TypeCode.Single, true) => static value => checked((float)(float)value!),
            (TypeCode.Single, TypeCode.Double, false) => static value => unchecked((double)(float)value!),
            (TypeCode.Single, TypeCode.Double, true) => static value => checked((double)(float)value!),
            (TypeCode.Double, TypeCode.SByte, false) => static value => unchecked((sbyte)(double)value!),
            (TypeCode.Double, TypeCode.SByte, true) => static value => checked((sbyte)(double)value!),
            (TypeCode.Double, TypeCode.Byte, false) => static value => unchecked((byte)(double)value!),
            (TypeCode.Double, TypeCode.Byte, true) => static value => checked((byte)(double)value!),
            (TypeCode.Double, TypeCode.Int16, false) => static value => unchecked((short)(double)value!),
            (TypeCode.Double, TypeCode.Int16, true) => static value => checked((short)(double)value!),
            (TypeCode.Double, TypeCode.UInt16, false) => static value => unchecked((ushort)(double)value!),
            (TypeCode.Double, TypeCode.UInt16, true) => static value => checked((ushort)(double)value!),
            (TypeCode.Double, TypeCode.Int32, false) => static value => unchecked((int)(double)value!),
            (TypeCode.Double, TypeCode.Int32, true) => static value => checked((int)(double)value!),
            (TypeCode.Double, TypeCode.UInt32, false) => static value => unchecked((uint)(double)value!),
            (TypeCode.Double, TypeCode.UInt32, true) => static value => checked((uint)(double)value!),
            (TypeCode.Double, TypeCode.Int64, false) => static value => unchecked((long)(double)value!),
            (TypeCode.Double, TypeCode.Int64, true) => static value => checked((long)(double)value!),
            (TypeCode.Double, TypeCode.UInt64, false) => static value => unchecked((ulong)(double)value!),
            (TypeCode.Double, TypeCode.UInt64, true) => static value => checked((ulong)(double)value!),
            (TypeCode.Double, TypeCode.Char, false) => static value => unchecked((char)(double)value!),
            (TypeCode.Double, TypeCode.Char, true) => static value => checked((char)(double)value!),
            (TypeCode.Double, TypeCode.Single, false) => static value => unchecked((float)(double)value!),
            (TypeCode.Double, TypeCode.Single, true) => static value => checked((float)(double)value!),
            (TypeCode.Double, TypeCode.Double, false) => static value => unchecked((double)(double)value!),
            (TypeCode.Double, TypeCode.Double, true) => static value => checked((double)(double)value!),
            _ => null
        };

    internal static Func<object?, object?>? Unary(ExpressionType nodeType, TypeCode type) =>
        (nodeType, type) switch
        {
            (ExpressionType.Negate, TypeCode.SByte) => static value => unchecked((sbyte)(-(sbyte)value!)),
            (ExpressionType.NegateChecked, TypeCode.SByte) => static value => checked((sbyte)(-(sbyte)value!)),
            (ExpressionType.Negate, TypeCode.Int16) => static value => unchecked((short)(-(short)value!)),
            (ExpressionType.NegateChecked, TypeCode.Int16) => static value => checked((short)(-(short)value!)),
            (ExpressionType.Negate, TypeCode.Int32) => static value => unchecked(-(int)value!),
            (ExpressionType.NegateChecked, TypeCode.Int32) => static value => checked(-(int)value!),
            (ExpressionType.Negate, TypeCode.Int64) => static value => unchecked(-(long)value!),
            (ExpressionType.NegateChecked, TypeCode.Int64) => static value => checked(-(long)value!),
            (ExpressionType.Negate, TypeCode.Single) => static value => unchecked(-(float)value!),
            (ExpressionType.NegateChecked, TypeCode.Single) => static value => checked(-(float)value!),
            (ExpressionType.Negate, TypeCode.Double) => static value => unchecked(-(double)value!),
            (ExpressionType.NegateChecked, TypeCode.Double) => static value => checked(-(double)value!),
            (ExpressionType.Not, TypeCode.SByte) => static value => (sbyte)(~(sbyte)value!),
            (ExpressionType.OnesComplement, TypeCode.SByte) => static value => (sbyte)(~(sbyte)value!),
            (ExpressionType.Not, TypeCode.Byte) => static value => (byte)(~(byte)value!),
            (ExpressionType.OnesComplement, TypeCode.Byte) => static value => (byte)(~(byte)value!),
            (ExpressionType.Not, TypeCode.Int16) => static value => (short)(~(short)value!),
            (ExpressionType.OnesComplement, TypeCode.Int16) => static value => (short)(~(short)value!),
            (ExpressionType.Not, TypeCode.UInt16) => static value => (ushort)(~(ushort)value!),
            (ExpressionType.OnesComplement, TypeCode.UInt16) => static value => (ushort)(~(ushort)value!),
            (ExpressionType.Not, TypeCode.Int32) => static value => ~(int)value!,
            (ExpressionType.OnesComplement, TypeCode.Int32) => static value => ~(int)value!,
            (ExpressionType.Not, TypeCode.UInt32) => static value => ~(uint)value!,
            (ExpressionType.OnesComplement, TypeCode.UInt32) => static value => ~(uint)value!,
            (ExpressionType.Not, TypeCode.Int64) => static value => ~(long)value!,
            (ExpressionType.OnesComplement, TypeCode.Int64) => static value => ~(long)value!,
            (ExpressionType.Not, TypeCode.UInt64) => static value => ~(ulong)value!,
            (ExpressionType.OnesComplement, TypeCode.UInt64) => static value => ~(ulong)value!,
            (ExpressionType.Not, TypeCode.Boolean) => static value => BooleanBoxes.Box(!(bool)value!),
            _ => null
        };
}
#endif
