<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsPackable>false</IsPackable>
        <LangVersion>latest</LangVersion>
        <NoWarn>BL0006;CA2252;IDE0032;IDE0079</NoWarn>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Epiforge.Extensions.Blazor\Epiforge.Extensions.Blazor.csproj" />
        <ProjectReference Include="..\Epiforge.Extensions.Collections\Epiforge.Extensions.Collections.csproj" Condition="'$(ReleasedExpressions)' == ''" />
        <ProjectReference Include="..\Epiforge.Extensions.Components\Epiforge.Extensions.Components.csproj" Condition="'$(ReleasedExpressions)' == ''" />
        <ProjectReference Include="..\Epiforge.Extensions.Expressions\Epiforge.Extensions.Expressions.csproj" Condition="'$(ReleasedExpressions)' == ''" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
        <PackageReference Include="DynamicData" Version="9.4.33" />
        <PackageReference Include="Epiforge.Extensions.Expressions" Version="$(ReleasedExpressions)" Condition="'$(ReleasedExpressions)' != ''" />
        <PackageReference Include="Linq.Expression.Optimizer" Version="1.0.29" />
        <PackageReference Include="NMF-Expressions" Version="2.3.0" />
        <PackageReference Include="ObservableComputations" Version="2.3.0" />
        <PackageReference Include="Phork.Blazor.Reactivity" Version="1.1.3" />
    </ItemGroup>

</Project>
