var builder = WebApplication.CreateBuilder(args);
builder.Services.AddRazorComponents().AddInteractiveServerComponents();
builder.Services.AddScoped<RenderLedger>();
builder.Services.AddScoped<WorkbenchState>();
Phork.Blazor.ServiceCollectionExtensions.AddPhorkBlazorReactivity(builder.Services);
var app = builder.Build();
app.UseAntiforgery();
app.MapStaticAssets();
app.MapRazorComponents<App>().AddInteractiveServerRenderMode();
app.Run();
