<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\Common\LibraryProject.props" />

    <PropertyGroup>
        <Product>Epiforge.Extensions.Expressions</Product>
        <Version>2.3.8</Version>
        <Description>This package assists in operating with expressions.</Description>
    </PropertyGroup>

    <PropertyGroup>
        <TargetFrameworks>net6.0;net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Epiforge.Extensions.Collections\Epiforge.Extensions.Collections.csproj" />
        <ProjectReference Include="..\Epiforge.Extensions.Components\Epiforge.Extensions.Components.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="System.Collections.Immutable" Version="8.0.0" />
    </ItemGroup>

</Project>
