<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\Common\LibraryProject.props" />

    <PropertyGroup>
        <Product>Epiforge.Extensions.Platforms.Windows</Product>
        <Version>3.0.0</Version>
        <PackageValidationBaselineVersion>2.0.1</PackageValidationBaselineVersion>
        <Description>This package assists in Windows-platform specific operations.</Description>
    </PropertyGroup>

    <PropertyGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <TargetFrameworks>net6.0-windows;net7.0-windows;net8.0-windows;net9.0-windows;net10.0-windows</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Epiforge.Extensions.Components\Epiforge.Extensions.Components.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="System.Management" Version="8.0.0" />
        <PackageReference Include="System.ValueTuple" Version="4.6.1" />
    </ItemGroup>

</Project>
